package com.b2c.mapper;

import com.b2c.model.ScoreDetail;
import com.b2c.model.ScoreDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScoreDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    long countByExample(ScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    int deleteByExample(ScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    int insert(ScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    int insertSelective(ScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    List<ScoreDetail> selectByExample(ScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    ScoreDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") ScoreDetail record, @Param("example") ScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    int updateByExample(@Param("record") ScoreDetail record, @Param("example") ScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(ScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_detail
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    int updateByPrimaryKey(ScoreDetail record);
}