package com.b2c.mapper;

import com.b2c.model.UserScore;
import com.b2c.model.UserScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    long countByExample(UserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    int deleteByExample(UserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    int insert(UserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    int insertSelective(UserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    List<UserScore> selectByExample(UserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    UserScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") UserScore record, @Param("example") UserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    int updateByExample(@Param("record") UserScore record, @Param("example") UserScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(UserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    int updateByPrimaryKey(UserScore record);
}