package com.b2c.mapper;

import com.b2c.model.UserCart;
import com.b2c.model.UserCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    long countByExample(UserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    int deleteByExample(UserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    int insert(UserCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    int insertSelective(UserCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    List<UserCart> selectByExample(UserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    UserCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") UserCart record, @Param("example") UserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    int updateByExample(@Param("record") UserCart record, @Param("example") UserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(UserCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_cart
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    int updateByPrimaryKey(UserCart record);
}