package com.b2c.mapper;

import com.b2c.model.ProductDesc;
import com.b2c.model.ProductDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    long countByExample(ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int deleteByExample(ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int insert(ProductDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int insertSelective(ProductDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    List<ProductDesc> selectByExampleWithBLOBs(ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    List<ProductDesc> selectByExample(ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    ProductDesc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") ProductDesc record, @Param("example") ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ProductDesc record, @Param("example") ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int updateByExample(@Param("record") ProductDesc record, @Param("example") ProductDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(ProductDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int updateByPrimaryKeyWithBLOBs(ProductDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    int updateByPrimaryKey(ProductDesc record);
}