package com.b2c.model;

public class ProductDesc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_desc.id
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_desc.product_id
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_desc.product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    private String productDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_desc.id
     *
     * @return the value of product_desc.id
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_desc.id
     *
     * @param id the value for product_desc.id
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_desc.product_id
     *
     * @return the value of product_desc.product_id
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_desc.product_id
     *
     * @param productId the value for product_desc.product_id
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_desc.product_desc
     *
     * @return the value of product_desc.product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_desc.product_desc
     *
     * @param productDesc the value for product_desc.product_desc
     *
     * @mbg.generated Tue Jul 11 21:12:12 GMT+08:00 2017
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }
}