package com.b2c.model;

public class RollImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_image.id
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_image.title
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_image.http_url
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    private String httpUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_image.img_url
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_image.flag
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    private Byte flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_image.desc
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roll_image.category
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_image.id
     *
     * @return the value of roll_image.id
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_image.id
     *
     * @param id the value for roll_image.id
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_image.title
     *
     * @return the value of roll_image.title
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_image.title
     *
     * @param title the value for roll_image.title
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_image.http_url
     *
     * @return the value of roll_image.http_url
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public String getHttpUrl() {
        return httpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_image.http_url
     *
     * @param httpUrl the value for roll_image.http_url
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public void setHttpUrl(String httpUrl) {
        this.httpUrl = httpUrl == null ? null : httpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_image.img_url
     *
     * @return the value of roll_image.img_url
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_image.img_url
     *
     * @param imgUrl the value for roll_image.img_url
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_image.flag
     *
     * @return the value of roll_image.flag
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_image.flag
     *
     * @param flag the value for roll_image.flag
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_image.desc
     *
     * @return the value of roll_image.desc
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_image.desc
     *
     * @param desc the value for roll_image.desc
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roll_image.category
     *
     * @return the value of roll_image.category
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roll_image.category
     *
     * @param category the value for roll_image.category
     *
     * @mbg.generated Tue Jul 18 14:50:59 GMT+08:00 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}