package com.b2c.model;

import java.util.Date;

public class ScoreRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_rule.id
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_rule.rule_name
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    private String ruleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_rule.type
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_rule.score
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_rule.create_time
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_rule.create_user
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_rule.update_time
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_rule.update_user
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    private Integer updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_rule.flag
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    private Byte flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_rule.id
     *
     * @return the value of score_rule.id
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_rule.id
     *
     * @param id the value for score_rule.id
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_rule.rule_name
     *
     * @return the value of score_rule.rule_name
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_rule.rule_name
     *
     * @param ruleName the value for score_rule.rule_name
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_rule.type
     *
     * @return the value of score_rule.type
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_rule.type
     *
     * @param type the value for score_rule.type
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_rule.score
     *
     * @return the value of score_rule.score
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_rule.score
     *
     * @param score the value for score_rule.score
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_rule.create_time
     *
     * @return the value of score_rule.create_time
     *
     * @mbg.generated Thu Jul 27 20:07:28 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_rule.create_time
     *
     * @param createTime the value for score_rule.create_time
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_rule.create_user
     *
     * @return the value of score_rule.create_user
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_rule.create_user
     *
     * @param createUser the value for score_rule.create_user
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_rule.update_time
     *
     * @return the value of score_rule.update_time
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_rule.update_time
     *
     * @param updateTime the value for score_rule.update_time
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_rule.update_user
     *
     * @return the value of score_rule.update_user
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_rule.update_user
     *
     * @param updateUser the value for score_rule.update_user
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_rule.flag
     *
     * @return the value of score_rule.flag
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_rule.flag
     *
     * @param flag the value for score_rule.flag
     *
     * @mbg.generated Thu Jul 27 20:07:29 GMT+08:00 2017
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }
}