package com.b2c.model;

import java.util.Date;

public class UserScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score.id
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score.score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score.create_time
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score.update_time
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score.create_user
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score.update_user
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score.user_id
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score.id
     *
     * @return the value of user_score.id
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score.id
     *
     * @param id the value for user_score.id
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score.score
     *
     * @return the value of user_score.score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score.score
     *
     * @param score the value for user_score.score
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score.create_time
     *
     * @return the value of user_score.create_time
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score.create_time
     *
     * @param createTime the value for user_score.create_time
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score.update_time
     *
     * @return the value of user_score.update_time
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score.update_time
     *
     * @param updateTime the value for user_score.update_time
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score.create_user
     *
     * @return the value of user_score.create_user
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score.create_user
     *
     * @param createUser the value for user_score.create_user
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score.update_user
     *
     * @return the value of user_score.update_user
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score.update_user
     *
     * @param updateUser the value for user_score.update_user
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score.user_id
     *
     * @return the value of user_score.user_id
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score.user_id
     *
     * @param userId the value for user_score.user_id
     *
     * @mbg.generated Wed Jul 26 15:59:16 GMT+08:00 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}