package com.b2c.model;

public class UserCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cart.id
     *
     * @mbg.generated Sat Aug 05 13:52:40 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cart.product_id
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cart.count
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cart.user_id
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cart.id
     *
     * @return the value of user_cart.id
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cart.id
     *
     * @param id the value for user_cart.id
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cart.product_id
     *
     * @return the value of user_cart.product_id
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cart.product_id
     *
     * @param productId the value for user_cart.product_id
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cart.count
     *
     * @return the value of user_cart.count
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cart.count
     *
     * @param count the value for user_cart.count
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cart.user_id
     *
     * @return the value of user_cart.user_id
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cart.user_id
     *
     * @param userId the value for user_cart.user_id
     *
     * @mbg.generated Sat Aug 05 13:52:41 GMT+08:00 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}